FROM node:18.16.0-buster
LABEL maintainer="dev.ymmwmm@gmail.com"

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install && yarn cache clean

EXPOSE 8080

ENV NODE_ENV=development
ENV DB_CONNECTION_STRING="mongodb://quiz:quiz@localhost:27017/quiz?authMechanism=DEFAULT&authSource=admin"
ENV PORT=8080
ENV HOST=0.0.0.0

CMD [ "yarn", "docker:dev" ]