version: "3.5"
services:
  mongodb:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quiz
      - MONGO_INITDB_ROOT_PASSWORD=quiz
  api:
    build: 
      dockerfile: Dockerfile.dev
    image: mew1307/quiz-api:latest
    ports:
      - 8080:8080/tcp
    volumes:
      - ./app:/app/app
    environment:
      DB_CONNECTION_STRING: mongodb://quiz:quiz@mongodb:27017/quiz?authMechanism=DEFAULT&authSource=admin
      PORT: 8080
      APP_URL: http://localhost:8080
    depends_on:
      - mongodb